{% set name = "dvc-azure" %}
{% set version = "2.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0f07eda53c0576cb2da18af0c3cf43d79a2f16aa84a551969dc9f28fa7da358

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - dvc
    - adlfs >=2021.10.0
    - azure-identity >=1.4.0
    - knack

test:
  imports:
    - dvc_azure
  requires:
    - git
    - pip
    - portalocker >=1.6,<2.0 # Temporary; see discussion around <https://github.com/conda-forge/dvc-feedstock/pull/234#issuecomment-907311619>
  commands:
    - pip check
    - dvc version
    - dvc version | grep azure

about:
  home: https://github.com/iterative/dvc-azure
  summary: Azure plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
